# Generated by Django 2.1.5 on 2019-01-15 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190114_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=24)),
                ('date_exp', models.DateField()),
                ('cvv', models.CharField(max_length=10)),
                ('card_front', models.ImageField(upload_to='cards/')),
                ('card_back', models.ImageField(upload_to='cards/')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserProfile'),
        ),
    ]
