# Generated by Django 2.1.5 on 2019-01-15 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20190115_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_holder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
