# Generated by Django 2.1.5 on 2019-01-15 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0006_auto_20190115_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_code', models.CharField(max_length=30)),
                ('country_name', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('address', models.TextField(max_length=500)),
                ('passport_photo', models.ImageField(upload_to='passport_photo/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
