# Generated by Django 2.1.5 on 2019-01-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20190116_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
