# Generated by Django 2.1.5 on 2019-01-16 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_verification_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_verified',
        ),
    ]
