# Generated by Django 2.1.5 on 2019-01-16 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_remove_userprofile_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
    ]
