# Generated by Django 2.1.5 on 2019-01-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_remove_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='is_verified',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
