# Generated by Django 2.1.5 on 2019-01-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20190116_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='is_verified',
            field=models.BooleanField(default=False, max_length=1),
        ),
    ]
