# Generated by Django 2.1.5 on 2019-01-18 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0020_auto_20190116_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_currency', models.TextField(max_length=10)),
                ('source_amount', models.IntegerField()),
                ('destination_currency', models.CharField(max_length=10)),
                ('destination_amount', models.IntegerField()),
                ('receipt_code', models.CharField(max_length=40)),
                ('blockchain_wallet', models.CharField(max_length=50)),
                ('transaction_status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success')], max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
