# Generated by Django 2.1.5 on 2019-01-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='transaction_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success')], default='Pending', max_length=10),
        ),
    ]
