# Generated by Django 2.1.5 on 2019-01-18 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0022_auto_20190118_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_currency', models.CharField(choices=[('USD', 'USD'), ('IRR', 'IRR'), ('BTC', 'BTC')], max_length=10)),
                ('source_amount', models.IntegerField()),
                ('destination_currency', models.CharField(max_length=10)),
                ('destination_amount', models.IntegerField()),
                ('receipt_code', models.CharField(max_length=40)),
                ('blockchain_wallet', models.CharField(max_length=50)),
                ('transaction_status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success')], default='Pending', max_length=10)),
                ('card_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Card')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
