# Generated by Django 2.1.5 on 2019-01-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_auto_20190127_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='source_amount',
            field=models.CharField(max_length=60),
        ),
    ]
