# Generated by Django 2.1.5 on 2019-01-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_auto_20190127_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='destination_amount',
            field=models.CharField(max_length=70),
        ),
    ]
